#!/usr/bin/env python3
"""Generate a readable hook consolidation execution plan."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "registry" / "hook-consolidation-plan.md"


def load_json(relative_path: str) -> dict[str, Any]:
    return json.loads((ROOT / relative_path).read_text(encoding="utf-8"))


def candidate_title(candidate: dict[str, Any]) -> str:
    return (
        f"{candidate['event']} / {candidate['matcher'] or '(empty matcher)'} / "
        f"{candidate['bucket']}"
    )


def render_candidate(candidate: dict[str, Any]) -> list[str]:
    lines = [
        f"### {candidate_title(candidate)}",
        "",
        f"- Risk: `{candidate['risk']}`",
        f"- Score: `{candidate['score']}`",
        f"- Hooks: `{candidate['hook_count']}`",
        f"- Order span: `{candidate.get('first_order')}`-`{candidate.get('last_order')}`",
        f"- Contiguous within trigger: `{candidate.get('contiguous_within_trigger')}`",
        f"- Interleaved hooks: `{candidate.get('interleaved_hook_count', 0)}`",
        f"- LLM hooks: `{candidate['llm_hook_count']}`",
        f"- Recommendation: `{candidate['recommendation']}`",
        f"- Reason: {candidate['reason']}",
        "",
        "| order | priority | script | blocking | LLM | side effects |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for hook in candidate.get("hooks", []):
        lines.append(
            "| "
            + " | ".join(
                [
                    str(hook.get("order")),
                    str(hook.get("priority")),
                    f"`{hook.get('script')}`",
                    str(hook.get("blocking")),
                    str(hook.get("calls_llm")),
                    ", ".join(hook.get("side_effects", [])),
                ]
            )
            + " |"
        )
    interleaved_hooks = candidate.get("interleaved_hooks", [])
    if interleaved_hooks:
        lines.extend(
            [
                "",
                "Interleaved hooks that would change relative order if this group were wrapped directly:",
                "",
                "| order | priority | script | blocking | LLM | side effects |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        for hook in interleaved_hooks:
            lines.append(
                "| "
                + " | ".join(
                    [
                        str(hook.get("order")),
                        str(hook.get("priority")),
                        f"`{hook.get('script')}`",
                        str(hook.get("blocking")),
                        str(hook.get("calls_llm")),
                        ", ".join(hook.get("side_effects", [])),
                    ]
                )
                + " |"
            )
    lines.extend(["", ""])
    return lines


def select_candidates(candidates: list[dict[str, Any]], risk: str, limit: int) -> list[dict[str, Any]]:
    scoped = [candidate for candidate in candidates if candidate.get("risk") == risk]
    return sorted(scoped, key=lambda item: (-item["score"], item["event"], item["matcher"]))[:limit]


def select_recommendation(
    candidates: list[dict[str, Any]],
    recommendation: str,
    limit: int,
) -> list[dict[str, Any]]:
    scoped = [
        candidate
        for candidate in candidates
        if candidate.get("recommendation") == recommendation
    ]
    return sorted(scoped, key=lambda item: (-item["score"], item["event"], item["matcher"]))[:limit]


def generate_plan() -> str:
    report = load_json("registry/hook-consolidation-candidates.json")
    candidates = report.get("candidates", [])
    low = select_candidates(report.get("candidates", []), "low", 5)
    order_review = select_recommendation(candidates, "order-review-before-wrapper", 8)
    wrapper_ready = select_recommendation(candidates, "candidate-for-router-or-wrapper", 8)
    high = select_recommendation(candidates, "manual-review-only", 6)

    lines = [
        "<!-- generated by scripts/generate-hook-consolidation-plan.py; do not edit by hand -->",
        "",
        "# Hook Consolidation Plan",
        "",
        "This plan is generated from `registry/hook-consolidation-candidates.json`.",
        "It is an execution aid, not an instruction to merge hooks automatically.",
        "",
        "## Summary",
        "",
        "| metric | value |",
        "| --- | ---: |",
        f"| hooks analyzed | {report.get('hook_count')} |",
        f"| candidates | {report.get('candidate_count')} |",
        f"| low risk | {report.get('low_risk_count')} |",
        f"| medium risk | {report.get('medium_risk_count')} |",
        f"| high risk | {report.get('high_risk_count')} |",
        f"| wrapper-ready recommendations | {report.get('wrapper_ready_count')} |",
        f"| order-review recommendations | {report.get('order_review_count')} |",
        f"| manual-review recommendations | {report.get('manual_review_count')} |",
        "",
        "## Execution Order",
        "",
        "1. Start only with low-risk candidates that are non-blocking, P2, do not call external LLMs, and are contiguous within the same event/matcher trigger.",
        "2. Treat non-contiguous side-effect groups as order-review work before any wrapper migration.",
        "3. Move to medium-risk PostToolUse groups by introducing wrappers that preserve current hook order.",
        "4. Treat Stop and PreToolUse groups as manual-review-only until their output, timeout, and blocking semantics are documented.",
        "5. After each wrapper migration, regenerate `hooks-manifest.json`, `hooks-inventory.json`, `hook-consolidation-candidates.json`, and run `scripts/audit-claude-config.py`.",
        "",
        "## Phase 1: Low Risk",
        "",
    ]
    if low:
        for candidate in low:
            lines.extend(render_candidate(candidate))
    else:
        lines.extend(["No low-risk candidates found.", ""])

    lines.extend(["## Phase 2: Order Review Before Wrapper", ""])
    if order_review:
        for candidate in order_review:
            lines.extend(render_candidate(candidate))
    else:
        lines.extend(["No order-review candidates found.", ""])

    lines.extend(["## Phase 3: Wrapper-Ready Candidates", ""])
    if wrapper_ready:
        for candidate in wrapper_ready:
            lines.extend(render_candidate(candidate))
    else:
        lines.extend(["No wrapper-ready candidates found.", ""])

    lines.extend(["## Phase 4: Manual Review Only", ""])
    if high:
        for candidate in high:
            lines.extend(render_candidate(candidate))
    else:
        lines.extend(["No high-risk candidates found.", ""])

    lines.extend(
        [
            "## Non-Negotiable Constraints",
            "",
            "- Preserve event, matcher, hook order, timeout, async behavior, and status message semantics.",
            "- Do not merge P0 or blocking hooks without a dedicated behavior test or replay fixture.",
            "- Do not hide output from guards that currently warn or block the user.",
            "- Do not mix secret-bearing MCP/env configuration into generated reports.",
            "- Keep generated registry artifacts in sync with `scripts/audit-claude-config.py`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help=f"write {OUTPUT_PATH.relative_to(ROOT)}")
    args = parser.parse_args()

    rendered = generate_plan()
    if args.write:
        OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
